Bugfix/95 skos context
OnroerendErfgoed/pyramid_skosprovider pull request #96
Opened 2023-03-07 08:15 UTC by koenedaele

2023-03-07 08:17 UTC, koenedaele commented
@Wim-De-Clercq To make this test pass, I need to make the test get the SKOS context file from the testapp (the URL http://localhost/jsonld/context/skos is embedded in the payload and gets fetched by pyld). What's the best way to do that? Any examples I can follow?

2023-03-07 15:18 UTC, Wim-De-Clercq requested changes
enkel 2de comment is echt van belang.

2023-03-07 15:18 UTC, Wim-De-Clercq commented on tests/test_functional.py
> +        data = json.loads(res.body.decode('utf-8'))
In principe is het wel consistent met de rest van de testen, dus ik wil dit wel door de vingers zien en dat er in de toekomst eens een grotere cleanup gebeurt.

Maar de propere maniervoor deze blok had deze geweest:

```py
res = self.testapp.get(
    '/conceptschemes/TREES',
    headers={'Accept': 'application/ld+json'},
    status=200,  # er wordt sowieso getest op success state (200-299), maar als je specifiek voor 200 wilt testen kan dit...
)
assert 'application/ld+json' in res.headers['Content-Type']
data = res.json
```

2023-03-07 15:18 UTC, Wim-De-Clercq commented on tests/test_functional.py
> +            rsps = register_ctxt_callback(rsps, self.testapp)
return value kan gedropt worden.

2023-03-08 07:25 UTC, Wim-De-Clercq approved these changes

2023-03-08 09:13 UTC, merged